# Generated by Django 5.0.2 on 2025-05-03 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название приложения')),
                ('process_name', models.CharField(max_length=255, verbose_name='Имя процесса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_productive', models.BooleanField(default=False, verbose_name='Полезное приложение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KeyboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('key_pressed', models.CharField(max_length=50, verbose_name='Нажатая клавиша')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.application', verbose_name='Приложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность клавиатуры',
                'verbose_name_plural': 'Активности клавиатуры',
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.application', verbose_name='Приложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'is_active'], name='tracking_ap_user_id_6d2d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'is_productive'], name='tracking_ap_user_id_e36104_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['process_name'], name='tracking_ap_process_e03169_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'process_name')},
        ),
        migrations.AddIndex(
            model_name='keyboardactivity',
            index=models.Index(fields=['user', 'timestamp'], name='tracking_ke_user_id_1e5cee_idx'),
        ),
        migrations.AddIndex(
            model_name='keyboardactivity',
            index=models.Index(fields=['application', 'timestamp'], name='tracking_ke_applica_7e5828_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user', 'start_time'], name='tracking_ti_user_id_28851c_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user', 'end_time'], name='tracking_ti_user_id_9060d5_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'start_time'], name='tracking_us_user_id_2e59e4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'end_time'], name='tracking_us_user_id_69ed18_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['application', 'start_time'], name='tracking_us_applica_841c36_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['application', 'end_time'], name='tracking_us_applica_ccd74c_idx'),
        ),
    ]
