# Generated by Django 5.0.2 on 2025-05-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Длительность"
            ),
        ),
    ]
