# Generated by Django 5.0.2 on 2025-05-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_alter_useractivity_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="keyboard_presses",
            field=models.IntegerField(
                default=0, verbose_name="Количество нажатий клавиш"
            ),
        ),
    ]
