# Generated by Django 5.0.2 on 2025-06-04 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_useractivity_keyboard_presses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('client_info', models.JSONField(blank=True, default=dict, verbose_name='Информация о клиенте')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'QR Токен',
                'verbose_name_plural': 'QR Токены',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='tracking_qr_token_c24c6f_idx'), models.Index(fields=['expires_at'], name='tracking_qr_expires_1efd19_idx'), models.Index(fields=['is_used'], name='tracking_qr_is_used_aa2c6f_idx')],
            },
        ),
    ]
