# Generated by Django 5.0.1 on 2025-06-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_qrtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRToken',
        ),
    ]
